DROP DATABASE IF EXISTS easydb;
DROP USER IF EXISTS `easyadmin`@`%`;
CREATE DATABASE IF NOT EXISTS easydb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `easyadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `easydb`.* TO `easyadmin`@`%`;